{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMgu8qZJ5aw85L3nfoxTUrU",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bhavana-ux618/ai-bootcamp/blob/main/BudgetApp.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        " implementation of the classic **Budget App Project** from Python practice courses. It demonstrates strong understanding of:\n",
        "\n",
        "* **Object-Oriented Programming (OOP)**\n",
        "* Lists and dictionaries\n",
        "* String formatting\n",
        "* Data processing\n",
        "* Building text-based charts\n",
        "\n",
        "Here’s a breakdown of what your project does.\n",
        "\n",
        "---\n",
        "\n",
        "# Budget Category Class\n",
        "\n",
        "we created a `Category` class to represent different budget categories like:\n",
        "\n",
        "* Food\n",
        "* Clothing\n",
        "* Entertainment\n",
        "\n",
        "Each category stores transactions in a `ledger`.\n",
        "\n",
        "Example ledger entry:\n",
        "\n",
        "```python\n",
        "{\"amount\": 50, \"description\": \"Groceries\"}\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "# Constructor (`__init__`)\n",
        "\n",
        "```python\n",
        "def __init__(self, name):\n",
        "    self.name = name\n",
        "    self.ledger = []\n",
        "```\n",
        "\n",
        "This initializes:\n",
        "\n",
        "* `name` → category name\n",
        "* `ledger` → list of transactions\n",
        "\n",
        "Example:\n",
        "\n",
        "```python\n",
        "food = Category(\"Food\")\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "# Deposit Method\n",
        "\n",
        "```python\n",
        "def deposit(self, amount, description=\"\"):\n",
        "```\n",
        "\n",
        "Adds money into the category.\n",
        "\n",
        "Example:\n",
        "\n",
        "```python\n",
        "food.deposit(1000, \"Initial deposit\")\n",
        "```\n",
        "\n",
        "Stored as:\n",
        "\n",
        "```python\n",
        "{\"amount\": 1000, \"description\": \"Initial deposit\"}\n",
        "```\n",
        "\n",
        "Good practice:\n",
        "\n",
        "* Optional descriptions\n",
        "* Using dictionaries for clean transaction storage\n",
        "\n",
        "---\n",
        "\n",
        "# Withdraw Method\n",
        "\n",
        "```python\n",
        "def withdraw(self, amount, description=\"\"):\n",
        "```\n",
        "\n",
        "Subtracts money only if enough balance exists.\n",
        "\n",
        "You correctly:\n",
        "\n",
        "* Check funds first\n",
        "* Store withdrawals as negative numbers\n",
        "\n",
        "Example:\n",
        "\n",
        "```python\n",
        "food.withdraw(50, \"Snacks\")\n",
        "```\n",
        "\n",
        "Stored as:\n",
        "\n",
        "```python\n",
        "{\"amount\": -50, \"description\": \"Snacks\"}\n",
        "```\n",
        "\n",
        "This is excellent accounting logic.\n",
        "\n",
        "---\n",
        "\n",
        "# Balance Calculation\n",
        "\n",
        "```python\n",
        "def get_balance(self):\n",
        "    return sum(item[\"amount\"] for item in self.ledger)\n",
        "```\n",
        "\n",
        "This uses a generator expression to calculate the balance efficiently.\n",
        "\n",
        "Example:\n",
        "\n",
        "```python\n",
        "1000 - 50 = 950\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "# Transfer Method\n",
        "\n",
        "```python\n",
        "def transfer(self, amount, category):\n",
        "```\n",
        "\n",
        "Transfers money between categories.\n",
        "\n",
        "Example:\n",
        "\n",
        "```python\n",
        "food.transfer(100, clothing)\n",
        "```\n",
        "\n",
        "Automatically:\n",
        "\n",
        "* Withdraws from one category\n",
        "* Deposits into another\n",
        "* Adds transfer descriptions\n",
        "\n",
        "Very clean implementation.\n",
        "\n",
        "---\n",
        "\n",
        "# Fund Checking\n",
        "\n",
        "```python\n",
        "def check_funds(self, amount):\n",
        "```\n",
        "\n",
        "Prevents overspending.\n",
        "\n",
        "Returns:\n",
        "\n",
        "* `True` if enough balance\n",
        "* `False` otherwise\n",
        "\n",
        "This keeps your app safe from invalid withdrawals.\n",
        "\n",
        "---\n",
        "\n",
        "# String Representation (`__str__`)\n",
        "\n",
        "This is one of the best parts of your project.\n",
        "\n",
        "```python\n",
        "def __str__(self):\n",
        "```\n",
        "\n",
        "You formatted output professionally:\n",
        "\n",
        "Example:\n",
        "\n",
        "```text\n",
        "*************Food*************\n",
        "Initial deposit       1000.00\n",
        "Groceries              -50.25\n",
        "Total: 949.75\n",
        "```\n",
        "\n",
        "You used:\n",
        "\n",
        "* Center alignment\n",
        "* Width formatting\n",
        "* Decimal precision\n",
        "* Description trimming\n",
        "\n",
        "Important formatting techniques:\n",
        "\n",
        "```python\n",
        "f\"{self.name:*^30}\"\n",
        "```\n",
        "\n",
        "Centers title within 30 characters using `*`.\n",
        "\n",
        "```python\n",
        "f\"{item['amount']:>7.2f}\"\n",
        "```\n",
        "\n",
        "Formats amounts:\n",
        "\n",
        "* Right aligned\n",
        "* 2 decimal places\n",
        "\n",
        "This shows strong understanding of Python string formatting.\n",
        "\n",
        "---\n",
        "\n",
        "# Spend Chart Function\n",
        "\n",
        "```python\n",
        "def create_spend_chart(categories):\n",
        "```\n",
        "\n",
        "This creates a vertical bar chart showing spending percentages.\n",
        "\n",
        "Example output:\n",
        "\n",
        "```text\n",
        "Percentage spent by category\n",
        "100|\n",
        " 90|\n",
        " 80|\n",
        " 70| o\n",
        " 60| o\n",
        " 50| o\n",
        " 40| o\n",
        " 30| o  o\n",
        " 20| o  o  o\n",
        " 10| o  o  o\n",
        "  0| o  o  o\n",
        "    ----------\n",
        "     F  C  A\n",
        "     o  l  u\n",
        "     o  o  t\n",
        "     d  t  o\n",
        "        h\n",
        "        i\n",
        "        n\n",
        "        g\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "# Important Concepts Used\n",
        "\n",
        "## 1. List Comprehension\n",
        "\n",
        "```python\n",
        "sum(-item[\"amount\"] for item in category.ledger if item[\"amount\"] < 0)\n",
        "```\n",
        "\n",
        "Efficiently calculates withdrawals.\n",
        "\n",
        "---\n",
        "\n",
        "## 2. Percentage Rounding\n",
        "\n",
        "```python\n",
        "int((s / total_spent) * 10) * 10\n",
        "```\n",
        "\n",
        "Rounds down to nearest 10.\n",
        "\n",
        "Example:\n",
        "\n",
        "* 67% → 60\n",
        "* 94% → 90\n",
        "\n",
        "---\n",
        "\n",
        "## 3. Dynamic Chart Building\n",
        "\n",
        "You dynamically:\n",
        "\n",
        "* Calculate chart height\n",
        "* Handle different category name lengths\n",
        "* Build labels vertically\n",
        "\n",
        "This is advanced beginner/intermediate Python.\n",
        "\n",
        "---\n",
        "\n",
        "# Overall Skill Level\n",
        "\n",
        "Your project demonstrates:\n",
        "\n",
        "✅ Classes and objects\n",
        "✅ Encapsulation\n",
        "✅ Methods and attributes\n",
        "✅ List manipulation\n",
        "✅ String formatting\n",
        "✅ Control flow\n",
        "✅ Data visualization in text\n",
        "✅ Clean code organization\n",
        "\n",
        "This is a strong **beginner-to-intermediate Python project**.\n",
        "\n",
        "---\n",
        "\n",
        "# Possible Improvements\n",
        "\n",
        "Here are some ideas to make it even better:\n",
        "\n",
        "## Add Transaction Dates\n",
        "\n",
        "```python\n",
        "{\"amount\": 50, \"description\": \"Groceries\", \"date\": \"2026-05-22\"}\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "## Add Categories Automatically\n",
        "\n",
        "Create a manager class like:\n",
        "\n",
        "```python\n",
        "class BudgetApp:\n",
        "```\n",
        "\n",
        "to handle all categories together.\n",
        "\n",
        "---\n",
        "\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "Ii2fEq7X_GM9"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "dRHpjQ0c_CXF"
      },
      "outputs": [],
      "source": [
        "class Category:\n",
        "    def __init__(self, name):\n",
        "        self.name = name\n",
        "        self.ledger = []\n",
        "\n",
        "    def deposit(self, amount, description=\"\"):\n",
        "        \"\"\"\n",
        "        Adds a deposit to the ledger.\n",
        "        \"\"\"\n",
        "        self.ledger.append({\"amount\": amount, \"description\": description})\n",
        "\n",
        "    def withdraw(self, amount, description=\"\"):\n",
        "        \"\"\"\n",
        "        Adds a withdrawal to the ledger if there are sufficient funds.\n",
        "        Returns True if successful, False otherwise.\n",
        "        \"\"\"\n",
        "        if self.check_funds(amount):\n",
        "            self.ledger.append({\"amount\": -amount, \"description\": description})\n",
        "            return True\n",
        "        return False\n",
        "\n",
        "    def get_balance(self):\n",
        "        \"\"\"\n",
        "        Returns the current balance of the budget category.\n",
        "        \"\"\"\n",
        "        return sum(item[\"amount\"] for item in self.ledger)\n",
        "\n",
        "    def transfer(self, amount, category):\n",
        "        \"\"\"\n",
        "        Transfers funds from this category to another category if funds are sufficient.\n",
        "        Returns True if successful, False otherwise.\n",
        "        \"\"\"\n",
        "        if self.check_funds(amount):\n",
        "            self.withdraw(amount, f\"Transfer to {category.name}\")\n",
        "            category.deposit(amount, f\"Transfer from {self.name}\")\n",
        "            return True\n",
        "        return False\n",
        "\n",
        "    def check_funds(self, amount):\n",
        "        \"\"\"\n",
        "        Returns False if the amount is greater than the balance, True otherwise.\n",
        "        \"\"\"\n",
        "        return amount <= self.get_balance()\n",
        "\n",
        "    def __str__(self):\n",
        "        \"\"\"\n",
        "        Returns the formatted string representation of the budget category object.\n",
        "        \"\"\"\n",
        "        # Center the title in a 30-character line of asterisks\n",
        "        lines = [f\"{self.name:*^30}\"]\n",
        "\n",
        "        # Format each ledger entry\n",
        "        for item in self.ledger:\n",
        "            # First 23 chars of the description, left-aligned\n",
        "            desc = f\"{item['description'][:23]:<23}\"\n",
        "            # Amount with 2 decimal places, right-aligned to a max of 7 chars\n",
        "            amt = f\"{item['amount']:>7.2f}\"\n",
        "            lines.append(f\"{desc}{amt}\")\n",
        "\n",
        "        # Add the total balance at the bottom\n",
        "        lines.append(f\"Total: {self.get_balance()}\")\n",
        "\n",
        "        return \"\\n\".join(lines)\n",
        "\n",
        "\n",
        "def create_spend_chart(categories):\n",
        "    \"\"\"\n",
        "    Takes a list of categories and returns a formatted string bar chart\n",
        "    representing the percentage of withdrawals spent in each category.\n",
        "    \"\"\"\n",
        "    # Calculate the total spent per category (withdrawals only)\n",
        "    spent = []\n",
        "    for category in categories:\n",
        "        cat_spent = sum(-item[\"amount\"] for item in category.ledger if item[\"amount\"] < 0)\n",
        "        spent.append(cat_spent)\n",
        "\n",
        "    # Calculate total spent across all provided categories\n",
        "    total_spent = sum(spent)\n",
        "\n",
        "    # Calculate percentages rounded down to the nearest 10\n",
        "    percentages = []\n",
        "    for s in spent:\n",
        "        if total_spent > 0:\n",
        "            percentages.append(int((s / total_spent) * 10) * 10)\n",
        "        else:\n",
        "            percentages.append(0)\n",
        "\n",
        "    # Build the chart line by line\n",
        "    lines = [\"Percentage spent by category\"]\n",
        "\n",
        "    # Build the y-axis labels and bar sections\n",
        "    for i in range(100, -1, -10):\n",
        "        line = f\"{i:>3}| \"\n",
        "        for percent in percentages:\n",
        "            if percent >= i:\n",
        "                line += \"o  \"\n",
        "            else:\n",
        "                line += \"   \"\n",
        "        lines.append(line)\n",
        "\n",
        "    # Build the horizontal dividing line\n",
        "    lines.append(\"    \" + \"-\" * (1 + 3 * len(categories)))\n",
        "\n",
        "    # Determine the longest category name to establish the y-axis depth\n",
        "    max_name_length = max(len(category.name) for category in categories)\n",
        "    padded_names = [category.name.ljust(max_name_length) for category in categories]\n",
        "\n",
        "    # Build the vertical category labels\n",
        "    for i in range(max_name_length):\n",
        "        line = \"     \"\n",
        "        for name in padded_names:\n",
        "            line += name[i] + \"  \"\n",
        "        lines.append(line)\n",
        "\n",
        "    # Join the lines without a trailing newline character\n",
        "    return \"\\n\".join(lines)"
      ]
    }
  ]
}
