{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNvTY2yL8bL/BpwQ3CwyDgg",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bhavana-ux618/ai-bootcamp/blob/main/BST.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "rcdUtvga7g3y"
      },
      "outputs": [],
      "source": [
        " Binary Search Tree project is an excellent implementation of a classic **data structure** in computer science. It demonstrates:\n",
        "\n",
        "* recursion\n",
        "* tree traversal\n",
        "* searching algorithms\n",
        "* node manipulation\n",
        "* object-oriented programming\n",
        "\n",
        "This is a strong intermediate-level Python project.\n",
        "\n",
        "---\n",
        "\n",
        "# 🌳 Binary Search Tree (BST) Project\n",
        "\n",
        "A **Binary Search Tree** is a special type of binary tree where:\n",
        "\n",
        "* Left child values are smaller than the parent\n",
        "* Right child values are greater than the parent\n",
        "\n",
        "Example:\n",
        "\n",
        "```text\n",
        "        50\n",
        "       /  \\\n",
        "     30    70\n",
        "    / \\    / \\\n",
        "   20 40  60 80\n",
        "```\n",
        "\n",
        "This structure allows:\n",
        "\n",
        "* fast searching\n",
        "* insertion\n",
        "* deletion\n",
        "\n",
        "Average time complexity:\n",
        "\n",
        "* Search → `O(log n)`\n",
        "* Insert → `O(log n)`\n",
        "* Delete → `O(log n)`\n",
        "\n",
        "---\n",
        "\n",
        "# 🧱 `TreeNode` Class\n",
        "\n",
        "```python\n",
        "class TreeNode:\n",
        "```\n",
        "\n",
        "This class represents a single node in the tree.\n",
        "\n",
        "Each node contains:\n",
        "\n",
        "* a value (`key`)\n",
        "* a left child\n",
        "* a right child\n",
        "\n",
        "---\n",
        "\n",
        "## 🔹 Constructor\n",
        "\n",
        "```python\n",
        "def __init__(self, key):\n",
        "    self.key = key\n",
        "    self.left = None\n",
        "    self.right = None\n",
        "```\n",
        "\n",
        "When a node is created:\n",
        "\n",
        "* the key stores the data\n",
        "* left/right pointers start as `None`\n",
        "\n",
        "Example:\n",
        "\n",
        "```python\n",
        "node = TreeNode(10)\n",
        "```\n",
        "\n",
        "creates:\n",
        "\n",
        "```text\n",
        "10\n",
        "```\n",
        "\n",
        "with no children.\n",
        "\n",
        "---\n",
        "\n",
        "## 🔹 `__str__()` Method\n",
        "\n",
        "```python\n",
        "def __str__(self):\n",
        "    return str(self.key)\n",
        "```\n",
        "\n",
        "This makes nodes printable:\n",
        "\n",
        "```python\n",
        "print(node)\n",
        "```\n",
        "\n",
        "Output:\n",
        "\n",
        "```text\n",
        "10\n",
        "```\n",
        "\n",
        "instead of memory addresses like:\n",
        "\n",
        "```text\n",
        "<__main__.TreeNode object at ...>\n",
        "```\n",
        "\n",
        "Good usability improvement 👍\n",
        "\n",
        "---\n",
        "\n",
        "# 🌲 `BinarySearchTree` Class\n",
        "\n",
        "```python\n",
        "class BinarySearchTree:\n",
        "```\n",
        "\n",
        "This manages the entire tree.\n",
        "\n",
        "---\n",
        "\n",
        "# 🔹 Root Node\n",
        "\n",
        "```python\n",
        "self.root = None\n",
        "```\n",
        "\n",
        "Initially the tree is empty.\n",
        "\n",
        "The root is the topmost node.\n",
        "\n",
        "---\n",
        "\n",
        "# ➕ Insertion Logic\n",
        "\n",
        "## Internal Recursive Method\n",
        "\n",
        "```python\n",
        "def _insert(self, node, key):\n",
        "```\n",
        "\n",
        "You used recursion beautifully here.\n",
        "\n",
        "---\n",
        "\n",
        "## Base Case\n",
        "\n",
        "```python\n",
        "if node is None:\n",
        "    return TreeNode(key)\n",
        "```\n",
        "\n",
        "If we reach an empty spot:\n",
        "\n",
        "* create a new node\n",
        "\n",
        "---\n",
        "\n",
        "## Left Subtree\n",
        "\n",
        "```python\n",
        "if key < node.key:\n",
        "    node.left = self._insert(node.left, key)\n",
        "```\n",
        "\n",
        "Smaller values go left.\n",
        "\n",
        "---\n",
        "\n",
        "## Right Subtree\n",
        "\n",
        "```python\n",
        "elif key > node.key:\n",
        "    node.right = self._insert(node.right, key)\n",
        "```\n",
        "\n",
        "Larger values go right.\n",
        "\n",
        "---\n",
        "\n",
        "# 🔒 Public Insert Method\n",
        "\n",
        "```python\n",
        "def insert(self, key):\n",
        "    self.root = self._insert(self.root, key)\n",
        "```\n",
        "\n",
        "This hides recursion from the user.\n",
        "\n",
        "Cleaner API design 👍\n",
        "\n",
        "Users simply call:\n",
        "\n",
        "```python\n",
        "tree.insert(50)\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "# 🔍 Search Operation\n",
        "\n",
        "## Recursive Search\n",
        "\n",
        "```python\n",
        "def _search(self, node, key):\n",
        "```\n",
        "\n",
        "This works exactly like BST searching should.\n",
        "\n",
        "---\n",
        "\n",
        "## Base Case\n",
        "\n",
        "```python\n",
        "if node is None or node.key == key:\n",
        "    return node\n",
        "```\n",
        "\n",
        "Stops when:\n",
        "\n",
        "* key is found\n",
        "* or node doesn't exist\n",
        "\n",
        "---\n",
        "\n",
        "## Search Left\n",
        "\n",
        "```python\n",
        "if key < node.key:\n",
        "    return self._search(node.left, key)\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "## Search Right\n",
        "\n",
        "```python\n",
        "return self._search(node.right, key)\n",
        "```\n",
        "\n",
        "Efficient because half the tree is ignored each step.\n",
        "\n",
        "---\n",
        "\n",
        "# ❌ Delete Operation\n",
        "\n",
        "Deletion is the hardest BST operation, and you implemented it correctly 👏\n",
        "\n",
        "```python\n",
        "def _delete(self, node, key):\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "# 🧠 Three Deletion Cases\n",
        "\n",
        "---\n",
        "\n",
        "## 1️⃣ Node Has No Children\n",
        "\n",
        "Leaf node removal.\n",
        "\n",
        "Handled automatically by:\n",
        "\n",
        "```python\n",
        "return node.right\n",
        "```\n",
        "\n",
        "or\n",
        "\n",
        "```python\n",
        "return node.left\n",
        "```\n",
        "\n",
        "when both are `None`.\n",
        "\n",
        "---\n",
        "\n",
        "## 2️⃣ Node Has One Child\n",
        "\n",
        "You replace the node with its child:\n",
        "\n",
        "```python\n",
        "if node.left is None:\n",
        "    return node.right\n",
        "```\n",
        "\n",
        "or:\n",
        "\n",
        "```python\n",
        "elif node.right is None:\n",
        "    return node.left\n",
        "```\n",
        "\n",
        "Very clean implementation.\n",
        "\n",
        "---\n",
        "\n",
        "## 3️⃣ Node Has Two Children\n",
        "\n",
        "Most difficult case.\n",
        "\n",
        "You used the inorder successor method:\n",
        "\n",
        "```python\n",
        "node.key = self._min_value(node.right)\n",
        "```\n",
        "\n",
        "This finds the smallest value in the right subtree.\n",
        "\n",
        "Then you delete the duplicate:\n",
        "\n",
        "```python\n",
        "node.right = self._delete(node.right, node.key)\n",
        "```\n",
        "\n",
        "Excellent standard BST logic.\n",
        "\n",
        "---\n",
        "\n",
        "# 🔽 Minimum Value Helper\n",
        "\n",
        "```python\n",
        "def _min_value(self, node):\n",
        "```\n",
        "\n",
        "Traverses left until the smallest node is found:\n",
        "\n",
        "```python\n",
        "while node.left is not None:\n",
        "    node = node.left\n",
        "```\n",
        "\n",
        "Because in BST:\n",
        "\n",
        "* smallest values are always farthest left.\n",
        "\n",
        "---\n",
        "\n",
        "# 🔄 Inorder Traversal\n",
        "\n",
        "```python\n",
        "def _inorder_traversal(self, node, result):\n",
        "```\n",
        "\n",
        "This traversal visits:\n",
        "\n",
        "1. Left subtree\n",
        "2. Root\n",
        "3. Right subtree\n",
        "\n",
        "---\n",
        "\n",
        "# 📌 Important BST Property\n",
        "\n",
        "Inorder traversal of a BST gives values in sorted order.\n",
        "\n",
        "Example:\n",
        "\n",
        "```text\n",
        "50, 30, 70, 20, 40\n",
        "```\n",
        "\n",
        "becomes:\n",
        "\n",
        "```text\n",
        "20, 30, 40, 50, 70\n",
        "```\n",
        "\n",
        "Your code:\n",
        "\n",
        "```python\n",
        "result.append(node.key)\n",
        "```\n",
        "\n",
        "collects the sorted sequence.\n",
        "\n",
        "---\n",
        "\n",
        "# 🧠 Recursion Usage\n",
        "\n",
        "Your project heavily uses recursion.\n",
        "\n",
        "This is ideal for trees because:\n",
        "\n",
        "* trees are recursive structures\n",
        "* each subtree is itself a tree\n",
        "\n",
        "You correctly applied recursion in:\n",
        "\n",
        "* insertion\n",
        "* search\n",
        "* deletion\n",
        "* traversal\n",
        "\n",
        "---\n",
        "\n",
        "# 📚 Concepts Demonstrated\n",
        "\n",
        "Your project shows understanding of:\n",
        "\n",
        "* ✅ Classes & Objects\n",
        "* ✅ Recursive algorithms\n",
        "* ✅ Tree data structures\n",
        "* ✅ Binary Search Trees\n",
        "* ✅ Depth-first traversal\n",
        "* ✅ Encapsulation\n",
        "* ✅ Helper methods\n",
        "* ✅ Data organization\n",
        "* ✅ Algorithm design\n",
        "\n",
        "---\n",
        "\n",
        "# ⚡ Time Complexity\n",
        "\n",
        "| Operation | Average  | Worst |\n",
        "| --------- | -------- | ----- |\n",
        "| Insert    | O(log n) | O(n)  |\n",
        "| Search    | O(log n) | O(n)  |\n",
        "| Delete    | O(log n) | O(n)  |\n",
        "\n",
        "Worst case happens if the tree becomes unbalanced:\n",
        "\n",
        "```text\n",
        "1\n",
        " \\\n",
        "  2\n",
        "   \\\n",
        "    3\n",
        "```\n",
        "\n",
        "which behaves like a linked list.\n",
        "\n",
        "---\n",
        "\n",
        "# 🚀 Possible Improvements\n",
        "\n",
        "---\n",
        "\n",
        "## 🌟 Add Preorder & Postorder Traversals\n",
        "\n",
        "You currently have inorder traversal only.\n",
        "\n",
        "You could add:\n",
        "\n",
        "* preorder\n",
        "* postorder\n",
        "* level-order traversal\n",
        "\n",
        "---\n",
        "\n",
        "## 🌟 Add Tree Height Method\n",
        "\n",
        "```python\n",
        "def height(self):\n",
        "```\n",
        "\n",
        "to measure tree depth.\n",
        "\n",
        "---\n",
        "\n",
        "## 🌟 Self-Balancing Trees\n",
        "\n",
        "Upgrade to:\n",
        "\n",
        "* AVL Tree\n",
        "* Red-Black Tree\n",
        "\n",
        "to maintain `O(log n)` performance.\n",
        "\n",
        "---\n",
        "\n",
        "## 🌟 Visualization\n",
        "\n",
        "Print the tree structure visually:\n",
        "\n",
        "```text\n",
        "        50\n",
        "       /  \\\n",
        "     30    70\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "# 🏆 Overall Evaluation\n",
        "\n",
        "This is a strong computer science project because it demonstrates:\n",
        "\n",
        "* recursive thinking\n",
        "* algorithm implementation\n",
        "* understanding of tree structures\n",
        "* memory references/pointers\n",
        "* efficient searching techniques\n",
        "\n",
        "BSTs are foundational in:\n",
        "\n",
        "* databases\n",
        "* search engines\n",
        "* file systems\n",
        "* compilers\n",
        "* operating systems\n",
        "\n",
        "So this is a very valuable project for learning DSA (Data Structures & Algorithms).\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "class TreeNode:\n",
        "\n",
        "    def __init__(self, key):\n",
        "        self.key = key\n",
        "        self.left = None\n",
        "        self.right = None\n",
        "\n",
        "    def __str__(self):\n",
        "        return str(self.key)\n",
        "\n",
        "class BinarySearchTree:\n",
        "\n",
        "    def __init__(self):\n",
        "        self.root = None\n",
        "\n",
        "    def _insert(self, node, key):\n",
        "        if node is None:\n",
        "            return TreeNode(key)\n",
        "\n",
        "        if key < node.key:\n",
        "            node.left = self._insert(node.left, key)\n",
        "        elif key > node.key:\n",
        "\n",
        "            node.right = self._insert(node.right, key)\n",
        "        return node\n",
        "\n",
        "    def insert(self, key):\n",
        "        self.root = self._insert(self.root, key)\n",
        "\n",
        "    def _search(self, node, key):\n",
        "        if node is None or node.key == key:\n",
        "            return node\n",
        "        if key < node.key:\n",
        "            return self._search(node.left, key)\n",
        "        return self._search(node.right, key)\n",
        "\n",
        "    def search(self, key):\n",
        "        return self._search(self.root, key)\n",
        "\n",
        "    def _delete(self, node, key):\n",
        "        if node is None:\n",
        "            return node\n",
        "        if key < node.key:\n",
        "            node.left = self._delete(node.left, key)\n",
        "        elif key > node.key:\n",
        "            node.right = self._delete(node.right, key)\n",
        "        else:\n",
        "            if node.left is None:\n",
        "                return node.right\n",
        "            elif node.right is None:\n",
        "                return node.left\n",
        "\n",
        "            node.key = self._min_value(node.right)\n",
        "            node.right = self._delete(node.right, node.key)\n",
        "\n",
        "        return node\n",
        "\n",
        "    def delete(self, key):\n",
        "        self.root = self._delete(self.root, key)\n",
        "\n",
        "    def _min_value(self, node):\n",
        "        while node.left is not None:\n",
        "            node = node.left\n",
        "        return node.key\n",
        "\n",
        "    def _inorder_traversal(self, node, result):\n",
        "        if node:\n",
        "            self._inorder_traversal(node.left, result)\n",
        "            result.append(node.key)\n",
        "            self._inorder_traversal(node.right, result)\n",
        "\n",
        "    def inorder_traversal(self):\n",
        "        result = []\n",
        "        self._inorder_traversal(self.root, result)\n",
        "        return result"
      ],
      "metadata": {
        "id": "PNo12CJg7hX4"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
